alias_map = {
    "btc": "BTC/USD",
    "bitcoin": "BTC/USD",
    "eth": "ETH/USD",
    "ethereum": "ETH/USD",
    "xrp": "XRP/USD",
    "ripple": "XRP/USD",
    "ada": "ADA/USD",
    "cardano": "ADA/USD",
    "doge": "DOGE/USD",
    "dogecoin": "DOGE/USD",
    "sol": "SOL/USD",
    "solana": "SOL/USD",
    "usdc": "USDC/USD",
    "usdt": "USDT/USD",
    "tether": "USDT/USD",
    "bnb": "BNB/USD",
    "binance coin": "BNB/USD",
    "ltc": "LTC/USD",
    "litecoin": "LTC/USD",
    "link": "LINK/USD",
    "uniswap": "UNI/USD",
    "polkadot": "DOT/USD",
    "polygon": "MATIC/USD",
    "matic": "MATIC/USD",
    "shiba": "SHIB/USD",
    "shiba inu": "SHIB/USD",
    "tron": "TRX/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd": "USD/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD",
    "usd coin": "USDC/USD",
    "usd tether": "USDT/USD"
}

 